"""Build report.pdf from editable Markdown; preserve original plan as text and attachment."""
import argparse
import hashlib
from html import escape
import json
from pathlib import Path
import re
import subprocess
import sys
import textwrap

ROOT = Path(__file__).resolve().parent


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font-dir", type=Path, default=Path("C:/Windows/Fonts"))
    args = parser.parse_args()
    if sys.version_info[:3] != (3, 12, 10):
        parser.error("use Python 3.12.10")
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Preformatted, Spacer, PageBreak, Image, KeepTogether
    from pypdf import PdfReader, PdfWriter

    for name, filename in (("Body", "arial.ttf"), ("Heading", "arialbd.ttf"), ("Mono", "consola.ttf")):
        path = args.font_dir / filename
        if not path.is_file():
            parser.error(f"Unicode font missing: {path}. Supply --font-dir with these fonts.")
        pdfmetrics.registerFont(TTFont(name, str(path)))
    plan_path = ROOT / "docs/original_plan.md"
    plan_bytes = plan_path.read_bytes()
    # Git normalizes line endings; verify wording against the original baseline.
    original = subprocess.check_output(["git", "show", "14da723:docs/original_plan.md"], cwd=ROOT)
    if plan_bytes.replace(b"\r\n", b"\n") != original.replace(b"\r\n", b"\n"):
        parser.error("original plan differs from its preserved baseline")
    source = (ROOT / "docs/report.md").read_text(encoding="utf-8")
    descriptions = {
        "main.py": "real-time entry point", "make_figures.py": "headless entry point",
        "state.py": "SI state and validation", "integration.py": "integration and complete step",
        "contacts.py": "contact resolution and records", "rendering.py": "PyVista and scheduling",
        "validation.py": "numerical experiments and figures", "cli.py": "shared CLI parsing",
        "build_report.py": "PDF report builder", "final_verify.py": "final local check capture",
        "preserve_transcript.py": "byte-preserved session export", "package_submission.py": "archive with actual .git",
        "docs/report.md": "editable report narrative", "docs/original_plan.md": "original plan unchanged",
    }
    excluded = {".git", ".bug-worktrees", ".venv", "venv", "__pycache__", ".pytest_cache", "tmp", "submission"}
    layout = []
    for path in sorted(ROOT.rglob("*")):
        rel = path.relative_to(ROOT)
        if not path.is_file() or any(part in excluded for part in rel.parts):
            continue
        if path.name.startswith(("~", ".")) and path.name != ".gitignore":
            continue
        if path.name == "test.txt" or path.suffix in {".zip", ".pyc"} or rel.as_posix() == "docs/report.expanded.md":
            continue
        layout.append(f"{rel.as_posix()} - {descriptions.get(rel.as_posix(), 'supporting source, documentation, or evidence')}")
    if not (ROOT / "report.pdf").exists():
        layout.append("report.pdf - generated report (created by this build)")
    layout.append(".git/ - complete repository metadata; both local bug commits and helpers remain here")
    source = source.replace("{{FILE_LAYOUT}}", "```text\n" + "\n".join(layout) + "\n```")
    final_path = ROOT / "evidence/final/summary.json"
    if final_path.exists():
        result = json.loads(final_path.read_text(encoding="utf-8"))
        text = (f"Final local-run record: commit {result['commit']}; Python {result['python'].split()[0]}. "
                f"All commands passed: {result['all_passed']}. "
                + "; ".join(f"{run['name']} exit {run['exit_code']}" for run in result["runs"]) + ". "
                + "Installed versions: " + json.dumps(result["versions"], sort_keys=True)
                + ". These logs were generated by local execution, not by the agent's inspection.")
    else:
        text = "Final full-suite verification is pending. No final runtime pass is claimed."
    source = source.replace("{{FINAL_VERIFICATION}}", text)
    provenance = ("Actual session metadata identifies Codex (originator codex-tui, version 0.157.0, "
                  "source vscode, provider openai) and model gpt-6-astra in turn_context records. "
                  "The identifier is read from the original log, not guessed. See docs/provenance.md.")
    manifest_path = ROOT / "docs/transcript/manifest.json"
    if manifest_path.exists():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        provenance += (f" Raw transcript snapshot: docs/transcript/{manifest['file']}; "
                       f"SHA-256 {manifest['sha256']}. "
                       f"Final coverage confirmed by user: {manifest['final_coverage_confirmed_by_user']}.")
    else:
        provenance += " Complete raw transcript preservation remains pending."
    source = source.replace("{{PROVENANCE}}", provenance)
    # Expanded editable source includes the exact original text, not a rewritten plan.
    expanded = source.replace("{{ORIGINAL_PLAN}}", plan_bytes.decode("utf-8"))
    (ROOT / "docs/report.expanded.md").write_text(expanded, encoding="utf-8")

    body = ParagraphStyle("Body", fontName="Body", fontSize=10, leading=14, spaceAfter=8, alignment=TA_LEFT)
    heading = ParagraphStyle("Heading", parent=body, fontName="Heading", fontSize=16, leading=20, spaceBefore=10, keepWithNext=True)
    title = ParagraphStyle("Title", parent=heading, fontSize=24, leading=29, spaceAfter=18)
    code = ParagraphStyle("Code", fontName="Mono", fontSize=8, leading=10, spaceAfter=1)
    caption = ParagraphStyle("Caption", parent=body, fontSize=9, leading=12, textColor=colors.HexColor("#35445a"))
    story = []

    def literal(text):
        # Preserve all original characters. Only visual line wrapping is added.
        for line in text.splitlines():
            wrapped = textwrap.wrap(line, width=98, replace_whitespace=False,
                                    drop_whitespace=False, expand_tabs=False, break_on_hyphens=False) or [""]
            story.append(Preformatted("\n".join(wrapped), code))

    paragraph = []
    in_code = False

    def flush():
        if paragraph:
            story.append(Paragraph(escape(" ".join(paragraph)), body))
            paragraph.clear()

    for line in source.splitlines():
        if line == "{{ORIGINAL_PLAN}}":
            flush()
            literal(plan_bytes.decode("utf-8"))
        elif line.startswith("```"):
            flush()
            in_code = not in_code
        elif in_code:
            literal(line)
        elif not line.strip():
            flush()
        elif line.startswith("# "):
            flush()
            story.append(Paragraph(escape(line[2:]), title))
        elif line.startswith("## "):
            flush()
            if story:
                story.append(PageBreak())
            story.append(Paragraph(escape(line[3:]), heading))
        elif line.startswith("!["):
            flush()
            match = re.fullmatch(r"!\[(.*)\]\((.*)\)", line)
            if not match:
                raise ValueError(f"Malformed figure directive: {line}")
            figure = Image(str(ROOT / match[2]))
            scale = min(504 / figure.imageWidth, 440 / figure.imageHeight)
            figure.drawWidth = figure.imageWidth * scale
            figure.drawHeight = figure.imageHeight * scale
            story.append(KeepTogether([figure, Spacer(1, 6), Paragraph(escape(match[1]), caption)]))
        elif line.startswith("- "):
            flush()
            story.append(Paragraph(escape(line), body))
        else:
            paragraph.append(line)
    flush()
    temp = ROOT / "tmp/pdfs"
    temp.mkdir(parents=True, exist_ok=True)
    intermediate = temp / "report_body.pdf"

    def footer(canvas, doc):
        canvas.setFont("Body", 8)
        canvas.setFillColor(colors.HexColor("#607086"))
        canvas.drawString(54, 28, "Bouncing circle | evidence-based review draft")
        canvas.drawRightString(558, 28, str(doc.page))

    SimpleDocTemplate(str(intermediate), pagesize=letter, rightMargin=54, leftMargin=54,
                      topMargin=48, bottomMargin=48, title="Bouncing Circle Simulation").build(
                          story, onFirstPage=footer, onLaterPages=footer)
    writer = PdfWriter(clone_from=str(intermediate))
    writer.add_attachment("original_plan.md", plan_bytes)
    destination = ROOT / "report.pdf"
    with destination.open("wb") as stream:
        writer.write(stream)
    reader = PdfReader(destination)
    if reader.attachments["original_plan.md"][0] != plan_bytes:
        raise RuntimeError("Original-plan attachment verification failed")
    build_record = dict(pdf_sha256=hashlib.sha256(destination.read_bytes()).hexdigest(),
                        original_plan_sha256=hashlib.sha256(plan_bytes).hexdigest(), pages=len(reader.pages),
                        original_attachment_verified=True, pdf_visual_qa="pending")
    (ROOT / "docs/report_build.json").write_text(json.dumps(build_record, indent=2), encoding="utf-8")
    print(json.dumps(build_record, indent=2))
    print("PDF generated; inspect every page before marking visual QA complete.")


if __name__ == "__main__":
    main()
